### ISSUE TITLE
为什么出场率最高只有十几，是怎么计算的？

### ISSUE THREAD

**Issue by helishou** [DGP-Studio/Snap.Genshin.Website#9]

**Comment by AZhrZho** [comment]
你好，我是胡桃数据库数据统计后台的开发者，感谢你对胡桃数据库的关注。

胡桃数据库出场率计算公式为：某层某角色出场率 = 该层该角色上场次数 / 该层通关次数

传统意义上的角色出场率计算公式为：出场率 = 角色出场次数 / 持有该角色的玩家数量

胡桃数据库的计算方法与传统计算方法相比，反映的不是玩家主观上的选择偏好，而是客观地反应角色上场的宏观数据。你可以将其理解为“某角色在深渊中出现的频率”。

希望对你有所帮助。
